# Generated by Django 4.1.7 on 2023-03-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_brand_carcolor_carstatus_fuel_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='observation',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='carcolor',
            old_name='observation',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='observation',
            new_name='car_type',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='observation',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='transmission',
            old_name='observation',
            new_name='type_transmission',
        ),
        migrations.RemoveField(
            model_name='carstatus',
            name='observation',
        ),
        migrations.AddField(
            model_name='carstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=50)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealership.brand')),
                ('cartype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealership.cartype')),
            ],
        ),
    ]
