# Generated by Django 4.1.7 on 2023-03-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0004_remove_carmodel_cartype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='fuel_type',
            new_name='fuel',
        ),
    ]
