# Generated by Django 4.1.7 on 2023-03-29 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0005_rename_fuel_type_fuel_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='cartype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.cartype'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carcolor',
            name='color',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.brand'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='fuel',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='type_transmission',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CarVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_version', models.CharField(default='', max_length=50)),
                ('id_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.brand')),
                ('id_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.carmodel')),
            ],
        ),
    ]
