# Generated by Django 4.1.7 on 2023-03-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0008_carmodel_brand_carmodel_cartype_carversion_id_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='cartype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.cartype'),
        ),
        migrations.AlterField(
            model_name='carversion',
            name='id_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.brand'),
        ),
        migrations.AlterField(
            model_name='carversion',
            name='id_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.carmodel'),
        ),
    ]
