# Generated by Django 4.1.7 on 2023-03-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0009_alter_carmodel_brand_alter_carmodel_cartype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='carcolor',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='fuel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='type_transmission',
            field=models.CharField(default='', max_length=50),
        ),
    ]
