# Generated by Django 4.1.7 on 2023-04-01 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0011_remove_carversion_id_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carversion',
            old_name='id_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='carversion',
            old_name='car_version',
            new_name='model_version',
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isUsed', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.carcolor')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.carmodel')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.transmission')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.cartype')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.carversion')),
            ],
        ),
    ]
